In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
datos = np.random.randint(0,101,(20,2))


In [5]:
datos

array([[27, 28],
       [35, 85],
       [71, 92],
       [29, 31],
       [37, 10],
       [27, 24],
       [90, 85],
       [80, 68],
       [64, 86],
       [96, 84],
       [45, 19],
       [91, 40],
       [36, 99],
       [29, 88],
       [36, 38],
       [58, 58],
       [23, 31],
       [62, 76],
       [43, 57],
       [84,  1]])

In [6]:
modelo = MinMaxScaler()

In [7]:
type(modelo)

sklearn.preprocessing.data.MinMaxScaler

In [8]:
modelo.fit(datos)

/home/sandy/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [9]:
modelo.transform(datos)


array([[0.05479452, 0.2755102 ],
       [0.16438356, 0.85714286],
       [0.65753425, 0.92857143],
       [0.08219178, 0.30612245],
       [0.19178082, 0.09183673],
       [0.05479452, 0.23469388],
       [0.91780822, 0.85714286],
       [0.78082192, 0.68367347],
       [0.56164384, 0.86734694],
       [1.        , 0.84693878],
       [0.30136986, 0.18367347],
       [0.93150685, 0.39795918],
       [0.17808219, 1.        ],
       [0.08219178, 0.8877551 ],
       [0.17808219, 0.37755102],
       [0.47945205, 0.58163265],
       [0.        , 0.30612245],
       [0.53424658, 0.76530612],
       [0.2739726 , 0.57142857],
       [0.83561644, 0.        ]])

In [10]:
modelo.fit_transform(datos)

/home/sandy/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[0.05479452, 0.2755102 ],
       [0.16438356, 0.85714286],
       [0.65753425, 0.92857143],
       [0.08219178, 0.30612245],
       [0.19178082, 0.09183673],
       [0.05479452, 0.23469388],
       [0.91780822, 0.85714286],
       [0.78082192, 0.68367347],
       [0.56164384, 0.86734694],
       [1.        , 0.84693878],
       [0.30136986, 0.18367347],
       [0.93150685, 0.39795918],
       [0.17808219, 1.        ],
       [0.08219178, 0.8877551 ],
       [0.17808219, 0.37755102],
       [0.47945205, 0.58163265],
       [0.        , 0.30612245],
       [0.53424658, 0.76530612],
       [0.2739726 , 0.57142857],
       [0.83561644, 0.        ]])

In [11]:
import pandas as pd

In [12]:
datos = pd.DataFrame(data= np.random.randint(0,101,(20,4)), 
                    columns =['val1','val2','val3','clase'])

In [13]:
datos

val1  val2  val3  clase
0     50    52    16     95
1     18    72    46     36
2     99    79    52     16
3     52    57    24     60
4     82    55    53     67
5     26     0    76     56
6      3     2    40     69
7     44    27    62     89
8     19     1   100     73
9     94     4    39     98
10    80    39    92     59
11    55    25    74     10
12    98    45    51     95
13    32    37    41     88
14   100    92    74     69
15    51    28    24     68
16    47     1    99     67
17    43    80    16     43
18    88    65    30     93
19    87    67    86     30

In [14]:
X = datos[['val1','val2','val3']]
y = datos['clase']

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test,y_train,y_test = train_test_split(X,y, 
                                                 test_size=0.4,
                                                 random_state = 10)

In [17]:
X_train.shape

(12, 3)

In [18]:
X_test.shape

(8, 3)